name: Deploy to App Runner - Source # Name of the workflow
on:
  push:
    branches: [main] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # Configure with AWS Credentials
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

#       - name: Deploy to App Runner
#         id: apprunner-github-action-sourcecode-demo
#         uses: DmitryGulin/amazon-app-runner-deploy@main # Deploy app runner service
#         env:
#           SERVER_PORT: 80
#         with:
#           service: apprunner-github-action-sourcecode-demo
#           source-connection-arn: ${{ secrets.AWS_CONNECTION_SOURCE_ARN }}
#           repo: https://github.com/${{ github.repository }}
#           branch: ${{ github.ref }}
#           runtime: NODEJS_16
#           build-command: npm ci && npm run build
#           start-command: npm start
#           port: ${{ env.SERVER_PORT }}
#           region: ${{ secrets.AWS_REGION }}
#           cpu: 1
#           memory: 2
#           wait-for-service-stability: true
#           copy-env-vars: |
#             SERVER_PORT

#       - name: App Runner output
#         run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}"
